// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowserOpenURL(arg1:string):Promise<void>;

export function CheckForUpdates():Promise<main.UpdateResult>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function GetFile(arg1:string):Promise<Array<number>>;

export function InstallUpdate(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SelectFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function StampPDF(arg1:string,arg2:Array<main.StampInfo>):Promise<string>;

export function UpdatePDFPages(arg1:string,arg2:Array<string>):Promise<string>;
