// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1) {
  return window['go']['main']['App']['BrowserOpenURL'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetFile(arg1) {
  return window['go']['main']['App']['GetFile'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function SelectFiles(arg1, arg2) {
  return window['go']['main']['App']['SelectFiles'](arg1, arg2);
}

export function StampPDF(arg1, arg2) {
  return window['go']['main']['App']['StampPDF'](arg1, arg2);
}

export function UpdatePDFPages(arg1, arg2) {
  return window['go']['main']['App']['UpdatePDFPages'](arg1, arg2);
}
